---
abstract: 'create an ebook in the MOBI format.'
author:
  - 'Boris Däppen <bdaeppen.perl@gmail.com>'
build_requires:
  Encode: 0
  File::Slurp: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132140'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EBook-MOBI
requires:
  Carp: 0
  File::Basename: 0
  File::Copy: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  GD: 0
  HTML::Entities: 0
  HTML::TreeBuilder: 0
  IO::String: 0
  Image::BMP: 0
  Image::Size: 0
  Pod::Parser: 0
  Text::Trim: 0
  constant: 0
  feature: 0
  lib: 0
  strict: 0
  vars: 0
  warnings: 0
version: 0.67
