---
abstract: 'create an ebook in the MOBI format.'
author:
  - 'Boris Däppen <boris_daeppen@bluewin.ch>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EBook-MOBI
requires:
  Carp: 1.11
  Data::Random: 0.05
  File::Basename: 2.77
  File::Copy: 2.14
  File::Find: 1.14
  File::Spec: 3.30
  File::Temp: 0.22
  FindBin: 1.5
  GD: 2.39
  HTML::Entities: 3.64
  HTML::TreeBuilder: 3.23
  IO::String: 1.08
  Image::BMP: 1.01
  Image::Resize: 0.5
  Image::Size: 3.221
  Pod::Coverage: 0.21
  Pod::Parser: 1.37
  Test::More: 0.98
  Test::Pod: 1.00
  Test::Pod::Coverage: 1.08
  Text::Trim: 1.02
version: 0.51
