---
abstract: 'create an eBook in the MOBI format - out of POD formatted content.'
author:
  - 'Boris Däppen <boris_daeppen@bluewin.ch>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EBook-MOBI
requires:
  Carp: 1.11
  Data::Random: 0.05
  File::Basename: 2.77
  File::Spec: 3.30
  File::Temp: 0.22
  HTML::Entities: 3.64
  IO::String: 1.08
  Image::Resize: 0.5
  Pod::Parser: 1.37
  Text::Trim: 1.02
version: 0.1
